service: claptime-users

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'staging'}
  region: ${opt:region, 'eu-west-1'}
  versionFunctions: false
  environment:
    STAGE: ${self:provider.stage}
    GRAPHQL_ENDPOINT: ${file(serverless-helpers.js):getApiEndpoint}
    ENABLED: ${file(serverless-helpers.js):getEnabled}
  iamRoleStatements:
    - Effect: Allow
      Action: ssm:GetParameter
      Resource:
        - ${self:custom.ssmPrefix}/${self:provider.stage}/mailchimp-api-key
        - ${self:custom.ssmPrefix}/staging/mailchimp-api-key
        - ${self:custom.ssmPrefix}/${self:provider.stage}/mailchimp-audience-id
        - ${self:custom.ssmPrefix}/staging/mailchimp-audience-id
        - ${self:custom.ssmPrefix}/${self:provider.stage}/mailchimp-server-prefix
        - ${self:custom.ssmPrefix}/staging/mailchimp-server-prefix
        - ${self:custom.ssmPrefix}/${self:provider.stage}/labfilms-mailchimp-api-key
        - ${self:custom.ssmPrefix}/staging/labfilms-mailchimp-api-key
        - ${self:custom.ssmPrefix}/${self:provider.stage}/labfilms-mailchimp-audience-id
        - ${self:custom.ssmPrefix}/staging/labfilms-mailchimp-audience-id
        - ${self:custom.ssmPrefix}/${self:provider.stage}/labfilms-mailchimp-server-prefix
        - ${self:custom.ssmPrefix}/staging/labfilms-mailchimp-server-prefix
    - Effect: Allow
      Action: appsync:GraphQL
      Resource:
        - ${self:custom.appsyncPrefix}/Mutation/fields/updateUserSettings
        - ${self:custom.appsyncPrefix}/Mutation/fields/createNotification
        - ${self:custom.appsyncPrefix}/Query/fields/getProfile
        - ${self:custom.appsyncPrefix}/Query/fields/getUserSettings
    - Effect: Allow
      Action:
        - cognito-idp:AdminGetUser
      Resource: ${self:custom.cognitoUserPoolArn}
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: '*'

functions:
  notifications:
    handler: src/functions/notifications/index.handler
    environment:
      COGNITO_USERPOOL_ID: ${file(serverless-helpers.js):getCognitoUserPoolId}
      FROM_EMAIL: Claptime <hello@clap-time.com>
      REPLY_TO_EMAIL: Claptime <contact.claptime@gmail.com>
      HELP_CENTER_URL: https://claptime.slite.com/p/channel/AHqUp91QZuDZPMf2UijEwk

plugins:
  - serverless-stack-termination-protection

custom:
  accountId: ${file(serverless-helpers.js):getAccountId}
  appsyncPrefix: arn:aws:appsync:${self:provider.region}:${self:custom.accountId}:apis/${file(serverless-helpers.js):getApiId}/types
  cognitoUserPoolArn: arn:aws:cognito-idp:${file(serverless-helpers.js):getCognitoRegion}:${file(serverless-helpers.js):getAccountId}:userpool/${file(serverless-helpers.js):getCognitoUserPoolId}
  ssmPrefix: arn:aws:ssm:${self:provider.region}:${self:custom.accountId}:parameter
  serverlessTerminationProtection:
    stages:
      - prod
      - staging
